Install sample configs to /usr/share/pvc instead
Also clean up the old versions in the postinst as they are obsolete and
not needed going forward. These only ever served as reference for a
manual installation which itself is long-obsoleted, and thus can be put
somewhere less "important".

diff --git a/debian/pvc-daemon-node.postinst b/debian/pvc-daemon-node.postinst
--- a/debian/pvc-daemon-node.postinst
+++ b/debian/pvc-daemon-node.postinst
@@ -14,3 +14,6 @@ if systemctl is-active --quiet pvcnoded.service; then
 else
     echo "NOTE: The PVC node daemon (pvcnoded.service) has not been started; create a config file at /etc/pvc/pvcnoded.yaml then start it."
 fi
+
+# Clean up any old sample configs
+rm /etc/pvc/pvcnoded.sample.yaml || true
