Revamp formatting and linting on commit
Remove the prepare script, and run the two stages manually. Better
handle Black reformatting by doing a check (for the errcode) then
reformat and abort commit to review.

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -4,9 +4,16 @@ pushd $( git rev-parse --show-toplevel ) &>/dev/null
 
 ex=0
 
-./prepare
+./format check
 if [[ $? -ne 0 ]]; then
-    echo "Aborting commit due to formatting or linting errors."
+    ./format
+    echo "Black formatting change detected; review and recommit"
+    ex=1
+fi
+
+./lint
+if [[ $? -ne 0 ]]; then
+    echo "Linting error detected; correct and recommit"
     ex=1
 fi
 
